import LayoutClient from "./layoutClient";

// Styles
import "@/styles/fonts.css";
import "@/styles/globals.css";


export const metadata = {
  title: "NextJs App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) 
{
  return (
    <html lang="en">
      <body>
        <LayoutClient>
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}